spring:
  application:
    name: grpc-client-app

grpc:
  client:
    user-service:
      address: 'static://localhost:9090'
      negotiationType: plaintext

server:
  port: 8080

logging:
  level:
    com.study.grpc: DEBUG
    io.grpc: INFO

